export const TYPES ={
    READ_ALL_DATA:"READ_ALL_DATA",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_ONE_FROM_CART:"REMOVE_ONE_FROM_CART",
    REMOVE_ALL_FROM_CART:"REMOVE_ALL_FROM_CART",
    NO_DATA:"NO_DATA"
};
